name: Validate JSON

on: [pull_request]

jobs:
    verify-json-validation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: json-lint
              uses: ocular-d/json-linter@0.0.1
